import Vue from "vue";
import {
  DropdownPlugin,
  ProgressPlugin,
  BadgePlugin,
  ModalPlugin,
  VBPopoverPlugin,
  CollapsePlugin,
  TabsPlugin,
  SpinnerPlugin,
  FormCheckboxPlugin,
  FormPlugin,
  LayoutPlugin,
  TablePlugin,
  PaginationPlugin,
  MediaPlugin,
  NavbarPlugin,
  PaginationNavPlugin,
  PopoverPlugin,
  FormGroupPlugin,
  VBScrollspyPlugin,
  InputGroupPlugin,
  ButtonPlugin,
  FormInputPlugin,
  SidebarPlugin,
  CardPlugin,
  FormRadioPlugin,
  FormDatepickerPlugin,
  FormTextareaPlugin,
  FormSelectPlugin,
  EmbedPlugin,
  ButtonGroupPlugin,
} from "bootstrap-vue";

Vue.use(DropdownPlugin);
Vue.use(ProgressPlugin);
Vue.use(BadgePlugin);
Vue.use(ModalPlugin);
Vue.use(VBPopoverPlugin);
Vue.use(CollapsePlugin);
Vue.use(TabsPlugin);
Vue.use(SpinnerPlugin);
Vue.use(FormCheckboxPlugin);
Vue.use(FormPlugin);
Vue.use(LayoutPlugin);
Vue.use(TablePlugin);
Vue.use(PaginationPlugin);
Vue.use(MediaPlugin);
Vue.use(NavbarPlugin);
Vue.use(PaginationNavPlugin);
Vue.use(PopoverPlugin);
Vue.use(FormGroupPlugin);
Vue.use(VBScrollspyPlugin);
Vue.use(InputGroupPlugin);
Vue.use(ButtonPlugin);
Vue.use(FormInputPlugin);
Vue.use(SidebarPlugin);
Vue.use(CardPlugin);
Vue.use(FormRadioPlugin);
Vue.use(FormDatepickerPlugin);
Vue.use(FormTextareaPlugin);
Vue.use(FormSelectPlugin);
Vue.use(EmbedPlugin);
Vue.use(ButtonGroupPlugin);
